//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 colors.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 0 files.
  struct file {
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 3 images.
  struct image {
    /// Image `closeButton`.
    static let closeButton = Rswift.ImageResource(bundle: R.hostingBundle, name: "closeButton")
    /// Image `flashButton`.
    static let flashButton = Rswift.ImageResource(bundle: R.hostingBundle, name: "flashButton")
    /// Image `listButton`.
    static let listButton = Rswift.ImageResource(bundle: R.hostingBundle, name: "listButton")
    
    /// `UIImage(named: "closeButton", bundle: ..., traitCollection: ...)`
    static func closeButton(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.closeButton, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "flashButton", bundle: ..., traitCollection: ...)`
    static func flashButton(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.flashButton, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "listButton", bundle: ..., traitCollection: ...)`
    static func listButton(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.listButton, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  struct nib {
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 1 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `FoodItemCell`.
    static let foodItemCell: Rswift.ReuseIdentifier<FoodItemCell> = Rswift.ReuseIdentifier(identifier: "FoodItemCell")
    
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 3 view controllers.
  struct segue {
    /// This struct is generated for `ScanResults_Controller`, and contains static references to 1 segues.
    struct scanResults_Controller {
      /// Segue identifier `showTableView`.
      static let showTableView: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, ScanResults_Controller, ScanResults_TableController> = Rswift.StoryboardSegueIdentifier(identifier: "showTableView")
      
      /// Optionally returns a typed version of segue `showTableView`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func showTableView(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, ScanResults_Controller, ScanResults_TableController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.scanResults_Controller.showTableView, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    /// This struct is generated for `Scan_Controller`, and contains static references to 1 segues.
    struct scan_Controller {
      /// Segue identifier `showCameraView`.
      static let showCameraView: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, Scan_Controller, Scan_CamerController> = Rswift.StoryboardSegueIdentifier(identifier: "showCameraView")
      
      /// Optionally returns a typed version of segue `showCameraView`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func showCameraView(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, Scan_Controller, Scan_CamerController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.scan_Controller.showCameraView, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    /// This struct is generated for `StorageContent_Controller`, and contains static references to 1 segues.
    struct storageContent_Controller {
      /// Segue identifier `showTableView`.
      static let showTableView: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, StorageContent_Controller, StorageContent_TableController> = Rswift.StoryboardSegueIdentifier(identifier: "showTableView")
      
      /// Optionally returns a typed version of segue `showTableView`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func showTableView(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, StorageContent_Controller, StorageContent_TableController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.storageContent_Controller.showTableView, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 4 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    /// Storyboard `Scan`.
    static let scan = _R.storyboard.scan()
    /// Storyboard `Storage`.
    static let storage = _R.storyboard.storage()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    /// `UIStoryboard(name: "Scan", bundle: ...)`
    static func scan(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.scan)
    }
    
    /// `UIStoryboard(name: "Storage", bundle: ...)`
    static func storage(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.storage)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct nib {
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try storage.validate()
      try scan.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "Main"
      
      fileprivate init() {}
    }
    
    struct scan: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let cameraView = StoryboardViewControllerResource<Scan_CamerController>(identifier: "CameraView")
      let name = "Scan"
      let scanNavigation = StoryboardViewControllerResource<UIKit.UINavigationController>(identifier: "ScanNavigation")
      let scanResultsTableView = StoryboardViewControllerResource<ScanResults_TableController>(identifier: "ScanResultsTableView")
      let scanResultsView = StoryboardViewControllerResource<ScanResults_Controller>(identifier: "ScanResultsView")
      let scanView = StoryboardViewControllerResource<Scan_Controller>(identifier: "ScanView")
      
      func cameraView(_: Void = ()) -> Scan_CamerController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: cameraView)
      }
      
      func scanNavigation(_: Void = ()) -> UIKit.UINavigationController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: scanNavigation)
      }
      
      func scanResultsTableView(_: Void = ()) -> ScanResults_TableController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: scanResultsTableView)
      }
      
      func scanResultsView(_: Void = ()) -> ScanResults_Controller? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: scanResultsView)
      }
      
      func scanView(_: Void = ()) -> Scan_Controller? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: scanView)
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "flashButton") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'flashButton' is used in storyboard 'Scan', but couldn't be loaded.") }
        if UIKit.UIImage(named: "closeButton") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'closeButton' is used in storyboard 'Scan', but couldn't be loaded.") }
        if UIKit.UIImage(named: "listButton") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'listButton' is used in storyboard 'Scan', but couldn't be loaded.") }
        if _R.storyboard.scan().scanNavigation() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'scanNavigation' could not be loaded from storyboard 'Scan' as 'UIKit.UINavigationController'.") }
        if _R.storyboard.scan().scanResultsView() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'scanResultsView' could not be loaded from storyboard 'Scan' as 'ScanResults_Controller'.") }
        if _R.storyboard.scan().scanView() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'scanView' could not be loaded from storyboard 'Scan' as 'Scan_Controller'.") }
        if _R.storyboard.scan().cameraView() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'cameraView' could not be loaded from storyboard 'Scan' as 'Scan_CamerController'.") }
        if _R.storyboard.scan().scanResultsTableView() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'scanResultsTableView' could not be loaded from storyboard 'Scan' as 'ScanResults_TableController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct storage: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "Storage"
      let storageContentTableView = StoryboardViewControllerResource<StorageContent_TableController>(identifier: "StorageContentTableView")
      let storageContentView = StoryboardViewControllerResource<StorageContent_Controller>(identifier: "StorageContentView")
      
      func storageContentTableView(_: Void = ()) -> StorageContent_TableController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: storageContentTableView)
      }
      
      func storageContentView(_: Void = ()) -> StorageContent_Controller? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: storageContentView)
      }
      
      static func validate() throws {
        if _R.storyboard.storage().storageContentView() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'storageContentView' could not be loaded from storyboard 'Storage' as 'StorageContent_Controller'.") }
        if _R.storyboard.storage().storageContentTableView() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'storageContentTableView' could not be loaded from storyboard 'Storage' as 'StorageContent_TableController'.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
